### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by qoforeit** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#108]
I am getting the following problem
```
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\pythonProject3\new.py", line 7, in <module>
    import arc
  File "C:\Users\Admin\PycharmProjects\pythonProject3\venv\lib\site-packages\arc\__init__.py", line 6, in <module>
    from .alkali_atom_data import *
  File "C:\Users\Admin\PycharmProjects\pythonProject3\venv\lib\site-packages\arc\alkali_atom_data.py", line 106, in <module>
    from .alkali_atom_functions import *
  File "C:\Users\Admin\PycharmProjects\pythonProject3\venv\lib\site-packages\arc\alkali_atom_functions.py", line 30, in <module>
    from .wigner import Wigner6j, Wigner3j, CG, WignerDmatrix
  File "C:\Users\Admin\PycharmProjects\pythonProject3\venv\lib\site-packages\arc\wigner.py", line 11, in <module>
    from sympy.physics.wigner import wigner_3j as Wigner3j_sympy
  File "C:\Users\Admin\PycharmProjects\pythonProject3\venv\lib\site-packages\sympy\__init__.py", line 195, in <module>
    from .geometry import (Point, Point2D, Point3D, Line, Ray, Segment, Line2D,
  File "C:\Users\Admin\PycharmProjects\pythonProject3\venv\lib\site-packages\sympy\geometry\__init__.py", line 13, in <module>
    from sympy.geometry.point import Point, Point2D, Point3D
ImportError: cannot import name 'Point' from 'sympy.geometry.point' (C:\Users\Admin\PycharmProjects\pythonProject3\venv\lib\site-packages\sympy\geometry\point.py)
```
Can you please help me

**Comment by nikolasibalic** [comment]
Hi @qoforeit ,

Thanks for message. This looks like some problem during dependancy installation, that I haven't seen before.
I need bit more information to be helpful.

Which Python version are you using?
And how you have installed ARC? Have you done installation from some IDE or from command line? 
Is this issue on fresh Python installation too?
Have you tried `pip install ARC-Alkali-Rydberg-Calculator --update --no-cache` ?
Can you check which `sympy` version you have installed? Maybe you can include output of `pip list` ?
Which Windows are you using? Which Python version are you using?

Many thanks,
Nikola

**Comment by qoforeit** [comment]
Dear Nikola,
Thanks for your reply. I am using Python 3.9.7. I install ARC from Pycharm
IDE.
sympy 1.9 is the version I am using.
I don't know how to include output of pip list ,could you please suggest me.
I am using windows10.

If you need any other information please let me know.

Thanks and regards
@qoforeit <https://github.com/qoforeit>

**Comment by nikolasibalic** [comment]
Hi @qoforeit and sorry for delay, I missed somehow Github notification.

I just did fresh install of Anaconda distribution of Python 3.9 on Windows 10 and installed arc from command line (Anaconda Prompt) using `pip install ARC-Alkali-Rydberg-Calculator` and successfully did `from arc import *` in Python.

This suggest that issue is with messed up installation of Python modules at your side. This happens, and to fix this I would suggest you to start with fresh Python installation if possible. If this is not possible, you can also alternatively use conda environments, e.g. you can type into Anaconda Prompt (assuming you have installed [Anaconda distribution of Python](https://www.anaconda.com/products/distribution)). 

```
conda create -n new_py39 python=3.9
conda activate new_py39
pip install ARC-Alkali-Rydberg-Calculator
python
>>> from arc import *
```
This creates new python environment called `new_py39`, enters that environment, installs ARC, opens python, and in Python then last line import ARC. That should help.

In particular, I recommend doing installation from simple terminal as IDEs sometimes break things (e.g. we used to have problems with Spyder in the past sometimes).

Hope this helps!

**Comment by qoforeit** [comment]
Thanks Nikola, now it's working fine.
