### ISSUE TITLE
getDipoleMatrixElement: wrong order of initial/final state arguments?

### ISSUE THREAD

**Issue by Dobrzyniecki** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#109]
The documentation for AlkaliAtom.getDipoleMatrixElement seems to contradict itself when it comes to the order of arguments. 

The current documentation for the function AlkaliAtom.getDipoleMatrixElement reads:

https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/blob/ddef0902ba5ea5900e868eaeae700b07332388f7/arc/alkali_atom_functions.py#L1040-L1045

The above definition, specifically lines 1044-1045, implies that:
the **first four** arguments, {n_1, l_1, j_1, mj_1}, shall be the quantum numbers of the **final** state (the bra); 
the **next four** arguments, {n_2, l_2, j_2, mj_2}, shall be the quantum numbers of the **initial** state (the ket). 

However, this seems to be wrong. The actual function takes these arguments in the opposite order -- to get the right result, you need to enter the initial state as {n_1, l_1, j_1, mj_1} and the final state as {n_2, l_2, j_2, mj_2}. 

To show this, we can take a look at the example given in the very same documentation: 

https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/blob/ddef0902ba5ea5900e868eaeae700b07332388f7/arc/alkali_atom_functions.py#L1064-L1073

The example states that for a transition with: 
**initial** state having m_j = -1/2, 
**final** state having m_j = -3/2,
and light polarization being sigma^- (i.e. the argument q = -1),
the right line of code to use is
`print(atom.getDipoleMatrixElement(5,0,0.5,-0.5,5,1,1.5,-1.5,-1))`
but that line has the initial state as {n_1, l_1, j_1, mj_1} and the final state as {n_2, l_2, j_2, mj_2} - contradicting the documentation lines 1044-1045. 

Am I misunderstanding something, or is this an error (either in the documentation or the function)? 

(It's also possible the same issue affects the function AlkaliAtom.getDipoleMatrixElementHFS.)

**Comment by nikolasibalic** [comment]
Hi @Dobrzyniecki ,

Thank you for reporting this. You are right, this might be bit confusing in context of how usually you would define sign of `q`, and implied initial and final state in the equations in the documentation. And you are right, the same convention, with initial state given as first state, and final state given as the second state, is used for `getDipoleMatrixElementHFS` too.

I have to think how best to resolve this. To update a code (which might break potentially some code that uses this) or amend appropriately equation in documentation (this might be better solution).

Best wishes,
Nikola

**Comment by nikolasibalic** [comment]
I was following your thinking initially about implied order when I agreed with you that it can be confusing.

Reviewing later this again, I don't agree with that this is implied. D.m.e. is symmetric, that is coupling does not imply direction of transition. Since format of coupling for different $q$ is not explicitly written in equation, and example is consistent with explicitly written order. Consistency within program is really only what matters.

I agree it's tricky to be sure about mapping of $\pm 1$ convention to coupling, but it's easy to check numerically to validate which convention is used. I don't see how to make it more obvious without adding too much text than can be more confusing than just testing which one of the two possible ways is working.

Closing this without changes.
