### ISSUE TITLE
Reduced Matrix Element convention

### ISSUE THREAD

**Issue by MelissaLAC** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#13]
Dear all,
I am a phd student working on de excitation of Cs Rydberg atoms using Black Body radiation.
I am using the atom calculator (downloaded essentially).
I noticed something, and I may be wrong but, it seems that on the web interface you mix the parenthesis notation for reduced matrix element and the notation with bra ket.
In quantum optics note by Steck, Chapter 7 (Atomic Angular Momentum Structure), page 330, equation (7.239), the link between the two notations is written, and is the reverse of what is appearing on the web interface. 
<img width="798" alt="steck_wignereckart" src="https://user-images.githubusercontent.com/33718427/32886510-28f9a31a-cac1-11e7-80c4-a03bf9184851.png">
<img width="459" alt="screenview_atomcalc_cs_21p_21s" src="https://user-images.githubusercontent.com/33718427/32886549-556dc87c-cac1-11e7-9be9-87b542af5ce4.png">
Hoping I am clear enough.

Let me know about this issue.
Thanks.

**Comment by nikolasibalic** [comment]
Hi @MelissaLAC,

Thank you for your comment. You are right, we are using exactly the opposite notation from Steck for two forms of reduced dipole matrix elements (one being symmetric upon change of order of j1 and j2, and the other one not). There is unfortunately no consistent notation on this in the literature if you look at angular momentum algebra books from different authors. That's why [Atom calculator](https://atomcalc.jqc.org.uk) returns numerical values for both so that people can easily spot if their preferred notation matches with our or not.

We've chosen to use < j1 || ... || j2 > for the reduced d.m.e. that has the same value when you change order of j1 and j2 because bra ket notation looks like you are taking matrix element, and matrix elements should be just one complex conjugate different. This reserves ( j1 || ... || j2 ) notation for reduced d.m.e whose numerical value is not equal to ( j2 || ... || j1 ) in general. This is opposite to Steck notation.

There is a note on this in [ARC documentation](http://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/alkali_atom_functions.html#arc.alkali_atom_functions.AlkaliAtom.getReducedMatrixElementJ_asymmetric) but it is good to have this noted here too as it often causes confusion. Thank you for your question and please let me know if something is unclear!

For your project, we have some [ARC black body examples here](http://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/_static/Rydberg_atoms_a_primer.html#Rydberg-Atom-Lifetimes). Good luck!

Best wishes, Nikola

**Comment by MelissaLAC** [comment]
Hi, 
Thank you very much for your fast answer. You're right that with the numerical values I could know which was which, and I am sorry that I didn't find the information why you choose these notations, I wouldn't have annoyed you! 
I will have a look to your BBR examples soon. 
Thank you again. 

Mélissa 


	Mélissa VIEILLE-GROSJEAN 
PhD student 
Laboratoire Aimé Cotton 
Bureau C02 


----- Mail original -----

De: "Nikola Šibalić" <notifications@github.com> 
À: "nikolasibalic/ARC-Alkali-Rydberg-Calculator" <ARC-Alkali-Rydberg-Calculator@noreply.github.com> 
Cc: "MelissaLAC" <melissa.vieille-grosjean@u-psud.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Jeudi 16 Novembre 2017 13:46:24 
Objet: Re: [nikolasibalic/ARC-Alkali-Rydberg-Calculator] Reduced Matrix Element convention (#13) 



Hi @MelissaLAC , 

Thank you for your comment. You are right, we are using exactly the opposite notation from Steck for two forms of reduced dipole matrix elements (one being symmetric upon change of order of j1 and j2, and the other one not). There is unfortunately no consistent notation on this in the literature if you look at angular momentum algebra books from different authors. That's why Atom calculator returns numerical values for both so that people can easily spot if their preferred notation matches with our or not. 

We've chosen to use < j1 || ... || j2 > for the reduced d.m.e. that has the same value when you change order of j1 and j2 because bra ket notation looks like you are taking matrix element, and matrix elements should be just one complex conjugate different. This reserves ( j1 || ... || j2 ) notation for reduced d.m.e whose numerical value is not equal to ( j2 || ... || j1 ) in general. This is opposite to Steck notation. 

There is a note on this in ARC documentation but it is good to have this noted here too as it often causes confusion. Thank you for your question and please let me know if something is unclear! 

For your project, we have some ARC black body examples here . Good luck! 

Best wishes, Nikola
