### ISSUE TITLE
Rb 87 transition frequency

### ISSUE THREAD

**Issue by kwnminho** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#20]
Hi,

Rydberg transition frequencies of Rb 87 measured in our lab disagree with the values I obtain by doing 

atom=Rubidum87()
atom.getTransitionFrequency( 5s1/2 to 97d5/2)

Disagreement is quite large : ~ 4.5 GHz. 

If I rather use atom=Rubidum85(), they agree within a few MHz. But I'm sure my experiment is done with Rb 87. Wondering if 'scaledRydbergconstant' in ARC package is somehow swapped?

Let me know if you have any idea. #

**Comment by nikolasibalic** [comment]
Hi @kwnminho 

Thank you for submitting this issue.

Problem was that ionisation energy of `Rubidium87` in the `arc/alkali_atom_data.py` was measured relative to the F=1 hyperfine state, whereas we want energy relative to centre of gravity of hyperfine manifold (because all of the transitions are calculated between **centres of gravity of hyperfine split states**). As you can see in correction (f5319ccf64386b76aaf340bcf2db2d2861d4b709), I had an extra minus sign in exponent, that caused offset of 4.271 GHz not to be correctly substracted originally. This offset was visible in energies of all states calculated from NIST ASD levels list, where energies are referenced to the ionisaiton energy from the ground state. In ARC these are states with principal quantum number smaller than `minQuantumDefectN`, which for Rubidium is 8. These states experienced this offset.

Therefore if you calculated transition frequency in Rb 87 from 5 S or 5 P state to high lying states, and had on offset relative to the measured experimental values (of the order of 4 GHz), commit f5319ccf64386b76aaf340bcf2db2d2861d4b709 resolves that.

New verison of ARC package that applies this solution is **2.0.5**. Please reinstall using pip with:

```
pip install ARC-Alkali-Rydberg-Calculator --upgrade --no-cache-dir
```

 Wheels for all operating systems (Mac, Windows, Linux from source) are pushed on PyPI now.

@kwnminho Please let me know if this solves the problem.

**Comment by kwnminho** [comment]
Hi @nikolasibalic 

Thanks for the prompt fix. It does bring the value lot closer to our measured values but 190 - 200 MHz offset still remains for the states I am comparing(5s1/2 to 84d5/2  and 5s1/2 to 97d5/2).

I am trying to understand what is going on. Because the magnitude is very close to 5p3/2 F=2 to F=3 splitting, I started looking into D2 line and came up with a question, which potentially be connected to remaining offset for Rydberg transition frequency.

With `atom=Rubidium87()`, `atom.getTransitionFrequency(5s1/2 to 5p3/2)` (pseudo code) gives me 384.230342 THz. Is this value from the center of gravity hfs of 5s1/2 to the center of gravity hfs of 5p3/2 as well? [Steck](https://steck.us/alkalidata/rubidium87numbers.1.6.pdf) has 5s1/2 to 5p3/2 frequency as 384.230484 THz so there is ~ 144 MHz difference between them. Please correct me if they are defined differently.

**Comment by nikolasibalic** [comment]
Note that [paper used for quantum defects](https://journals.aps.org/pra/abstract/10.1103/PhysRevA.67.052502) did fittings of D states up to n ~ 37. And they were able to fit measurements using just two quantum defect values (\delta_0 and \delta_2).

I am wondering now if fits were done for larger range of principal quantum numbers, if they were be different (and involve also more terms in fitting function, as it is sometimes used for other alkali metals)? By going to n = 84 and n = 97 you are going quite far from the original explored range.

I have no precise feeling could this account for residual 200 MHz - if someone has some comments on this, please write!

**Comment by nikolasibalic** [comment]
@kwnminho
