### ISSUE TITLE
Sign of C6 interaction using perturbation theory

### ISSUE THREAD

**Issue by HumpyBlumpy** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#22]
Hello, 
I believe there is a bug in the getC6perturbatively method: the result has the opposite sign of what it should be. 
I am comparing this with the pairinteraction package and my own code for perturbative C6 interactions and both give the opposite sign compared to ARC.

**Comment by nikolasibalic** [comment]
Hi @HumpyBlumpy ,

Thank you for submitting this issue. I think the difference may be just due to definition of C6, i.e. if you include minus sign in the definition of C6 or you include it in definition of potential. Note that [`getC6perturbatively`](https://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/calculations_atom_pairstate.html#arc.calculations_atom_pairstate.PairStateInteractions.getC6perturbatively) assumes that level shift is given by `V = - C_6/R^6`, for which C6 would be defined as stated in [example page](https://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/_static/Rydberg_atoms_a_primer.html#Dispersion-Coefficients). As I see, calculations are consistent with this.

What might caused a confusion was that in description of order of energies in [`energyDefect2`](https://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/alkali_atom_functions.html?highlight=getEnergyDefect2#arc.alkali_atom_functions.AlkaliAtom.getEnergyDefect2) documentation the order of energies used to be flipped, and seemed to have extra minus sign compared to [definition in example notebook](https://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/_static/Rydberg_atoms_a_primer.html#Rydberg-atom-interactions). This was just a mistake in documentation, that has been corrected now in e1932c6841a44a585cadeb18519117011b123a52. Calculations have always been done according to definition of energy defect  given in example notebook.

@HumpyBlumpy Please let me know if you agree that this resolves this issue.

**Comment by nikolasibalic** [comment]
I've added clarification in documentation now (8f85f474cbe97c3251b79c03699f37fda4ffa4e0). Now  the [new version of documentation](https://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/calculations_atom_pairstate.html#arc.calculations_atom_pairstate.PairStateInteractions.getC6perturbatively) has the point above explained explicitly. I hope that will prevent confusion.

**Comment by HumpyBlumpy** [comment]
Hi Nikola,

I missed the fact that the energy shift is defined with a negative sign.
That does indeed resolve the issue.

Thanks
