### ISSUE TITLE
No module named 'arc.arc_c_extensions'

### ISSUE THREAD

**Issue by jacobhines** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#23]
Hey @nikolasibalic,

In order to test some new functions I forked the repository and am working off the 2.0.5 commit. Running the code:
```python
import sys
rootDir = r'C:\Users\Jacob\Documents\ARC-Alkali-Rydberg-Calculator'
sys.path.insert(0,rootDir)

import arc
atom = arc.Caesium()
```
in Python 3.7.1 returns the (abbreviated) error:
```python
File "arc\alkali_atom_functions.py", line 175, in __init__
    from arc.arc_c_extensions import NumerovWavefunction
ImportError: No module named arc_c_extensions
```
This is the same error that was reported in a few issues. Issue #19 doesn't seem relevant because I'm not using pip. I've tried running some simple code through the command line and have encountered the same error, so I'm not sure its an issue with my config as was reported in #16. Issue #12 seems the most relevant but release [2.0.4](https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/releases) should have added support for Python 3.7, so I'm not sure why I would need to compile the c-extension myself.

Any thoughts?

Thanks,
Jacob

**Comment by nikolasibalic** [comment]
Hi @jacobhines 

Thank you for the issue, and for an effort to locate solution in previous issues.

I understand you want to develop new functions on top of the existing ARC code, and that's why you want to work directly with forked repository, and not a package from pip.

**Explanation why you see this...**

A part of ARC that does Numerov integration of wavefunctions is written as C extension. Packages published on PyPI (available via pip) are wheels, i.e. they contain compiled (pre-build) C code for multiple OS, architectures and Python versions. In that sense, Python 3.7 is supported. However, if you don't want to use wheel (as I understand above), you can build C extension yourself by running 

```
python setup.py  build_ext --inplace
```
This is easy on Linux (you need GNU compiler and Python dev headers) and OSX (you need Python dev headers and code development tools from OSX), but on Windows can be bit tricky to set up environment. I see from directory path above that you are on Windows.

**... and what is the shortest solution**

I recommend just to get build C extension from PyPI package. You can copy that *single file* into your local repository directory, and everything should work. Steps are:

1) Find on [package distribution](https://pypi.org/project/ARC-Alkali-Rydberg-Calculator/#files) files corresponding to your Python and OS and architecture. I think you need ```ARC_Alkali_Rydberg_Calculator-2.0.5-cp37-cp37m-win_amd64.whl``` that is Python 3.7, Windows, on 64bit architecture.
2) Unzip downloaded folder and you will find there in ```arc``` directory compiled file you need ```arc_c_extensions.cp37-win_amd64.pyd```. Copy this file in your local folder of forked ARC repository (copy into the ```...\ARC-Alkali-Rydberg-Calculator\arc``` directory) and you should be ready to go!

@jacobhines  please let me know if this resolves the issue, or there are problems encountered (I don't have Windows at hand to test this now).

Good luck with development, and don't hesitate to contact me if you have any further questions.
Nikola

**Comment by jacobhines** [comment]
Solved. Thanks for quickly answering my rookie question.

Best,
Jacob
