### ISSUE TITLE
angular dependency on Pair-state basis dimension

### ISSUE THREAD

**Issue by kwnminho** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#24]
I've been calculating pair-state energies for different thetas, and ran into unexpected behavior. ARC is doing fine for `theta = 0`, but for other angles say `theta = 0.5 * pi`, the matrix dimension gets huge. e.g. 1553 vs 34660.
State I'm looking into is Rb |97d5/2 mj=5/2, ,97d5/2, mj=5/2>,.

```python
nRyd = 97
lRyd = 2
jRyd = 2.5
mjRyd = 2.5
calc1 = PairStateInteractions(Rubidium(),
                              nRyd, lRyd, jRyd,
                              nRyd, lRyd, jRyd,
                              mjRyd, mjRyd, interactionsUpTo=1)
theta = 0
calc1.defineBasis(theta, 0., 4, 5, 7e9)
```
This prints out 
```
Calculating Hamiltonian matrix...
	matrix (dimension  1553 )
```

For same parameters except theta being `0.5*pi`, 

```python
calc1 = PairStateInteractions(Rubidium(),
                              nRyd, lRyd, jRyd,
                              nRyd, lRyd, jRyd,
                              mjRyd, mjRyd, interactionsUpTo=1)
theta = 0.5 * pi
calc1.defineBasis(theta, 0., 4, 5, 7e9)
```
which outputs
```
Calculating Hamiltonian matrix...
	matrix (dimension  34660 )
```

This seems to impose additional computation cost on diagonalization, and the result also doesn't look physical e.g. no r dependency. 

Any tips or comments are greatly appreciated!

**Comment by nikolasibalic** [comment]
Hi @kwnminho ,

Thank you for question! I will look tomorrow into more details about this, but here is a preliminary summary:

* Basis is expected to be bigger because M=m1+m2 is not anymore conserved.
* I tried quickly reducing the basis by taking smaller detuning range - I see there is level shift but smaller than in case `theta = 0`. This can be expected. I should add something to more easily highlight relevant state.
* If you work only at large distances (away from spaghetti region), you can use [`getC6perturbatively`](https://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/_static/Rydberg_atoms_a_primer.html#Dispersion-Coefficients). Unfortunately, I see that **I've introduced some bug in this function in recent updates, that breaks this function**. I will fix this!

I will try to fix mentioned bug, add clearer highlighting of the state, and check if there are any new beasts appearing. Will write then with more info here.

**Comment by nikolasibalic** [comment]
Hi @kwnminho 

I've pushed updates I wanted, and new version is available via pip.
For getting C6 quickly best is to use getC6perturbatively. E.g.

```python
n0 = 97
l0 = 2
j0 = 2.5
phi = 0 
dn = 10 
deltaMax = 25e9 

thetaList = np.linspace(0,2*np.pi,51)
mj = [2.5]
colourList = ["b","g","r"]

ax = plt.subplot(111, projection='polar')
ax.set_theta_zero_location("N")
line = []
    
for i in [0]:
    calculation = PairStateInteractions(Rubidium(),
                                        n0,l0,j0,n0,l0,j0,
                                        mj[i], mj[i])
    c6 = []
    for t in thetaList:
        C6=calculation.getC6perturbatively(t,phi, dn, deltaMax);
        c6.append(abs(C6))
    
    # plot results
    lineLegend, = plt.plot(thetaList,c6,"-",
                           color=colourList[i],label=("mj=%d/2"%int(2*mj[i])))
    line.append(lineLegend)
        
plt.legend(handles=line,fontsize=10)
plt.title("Rb, pairstate  97 $D_{5/2}$, $|C_6|$ in GHz $\mu$m$^{6}$",fontsize=10)
plt.show()
```
will give 

![97d_5_2_c6](https://user-images.githubusercontent.com/24477754/51191523-db28b900-18e4-11e9-908c-cd9ebad60b5d.png)

For going to full pair-state calculation, as mentioned earlier, M=m1+m2 is not conserved anymore. Hence we need to include more states in the basis. This will slow down calculation, but, how many states you need to include ultimately depends on how close your atoms are. Unfortunately, there is no simple criteria - you have to include more states (larger principal quantum number range and energy range) until you are satisfied with experimental results. This is because in spaghetti region there some pair-state, originally far off from the considered one, can approach this state due to interactions.

Example of simple calculation, that uses highlighting on logarithmic scale added in the new version, is

```python
nRyd = 97
lRyd = 2
jRyd = 2.5
mjRyd = 2.5
calc1 = PairStateInteractions(Rubidium(),
                              nRyd, lRyd, jRyd,
                              nRyd, lRyd, jRyd,
                              mjRyd, mjRyd, interactionsUpTo=1)
theta = 0
calc1.defineBasis(theta, 0., 4, 5, 7e9)

rvdw = calc1.getLeRoyRadius()
calc1.diagonalise(np.linspace(rvdw,10.0,100),200,progressOutput=True)

calc1.plotLevelDiagram(highlightScale='log-2')
calc1.ax.set_xlim(rvdw,10.0,)
calc1.ax.set_ylim(-2,2)
calc1.showPlot()
```

produces

![pair-state](https://user-images.githubusercontent.com/24477754/51191970-cbf63b00-18e5-11e9-8f69-d1026ecb2aec.png)

@kwnminho Let me know if this answers/helps with your question, so that this issue can be closed. Or otherwise, let me know if there are remaining problems.
