### ISSUE TITLE
Release 2.0.6 depends on numpy 1.16

### ISSUE THREAD

**Issue by dihm** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#25]
The wheel for the arc_c_extensions appears to have been compiled with numpy 1.16.x which involved a significant number of numpy API reorganizations over 1.15.x. When trying to run ARC with a lower version of numpy, code in the c_extension tries to load modules that have been renamed.

The explicit error I get running arc 2.0.6, python 3.6.8, and numpy 1.15.4 is
```python
import arc
atom = arc.Rubidium85()
  File "C:\Users\David\Miniconda3\envs\ARC\lib\site-packages\arc\alkali_atom_functions.py", line 175, in __init__
    from .arc_c_extensions import NumerovWavefunction
ImportError: numpy.core.multiarray failed to import
```
The explicit module it fails on is `numpy.core._multiarray_umath`. I was put on the right track by a comment deep down the thread of [this numpy issue.](https://github.com/numpy/numpy/issues/11871)

Downgrading ARC to 2.0.5 works as expected. Presumably running numpy up to 1.16 would also work, but it isn't mainline in conda yet so I've held off.

**Comment by nikolasibalic** [comment]
Hi @dihm ,

Thank you for the issue submission, and for finding root cause of the problem.

Indeed, built log shows that for Windows wheels were built with Numpy 1.16 whose lack of back-compatibility due to newly introduced modules causes issues. Until that is resolved on Numpy side, I restricted builds to old Numpy versions. The new version 2.0.7, available now on PyPI repository, should work.

Let me know if you experience more problems!
