### ISSUE TITLE
Issue with Look-up of Wigner6J Table

### ISSUE THREAD

**Issue by pbanner** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#42]
The calculation of 6-J symbols in the wigner module includes a look-up table that appears to make assumptions that certain inputs are integers, though they need not be. Thus many symbols, such as wigner.Wigner6j(1/2,1/2,1,2,1,3/2), will throw errors as those inputs are not integers. Specifically, line 215,
```python
return wignerPrecal6j[j1,
                      2 + j1 - J3,
                      int(roundPy2(2 + 2*(j3-j1))),
                      int(roundPy2(2 + 2*(J1-J3))),
                      J2 - 1,
                      int(roundPy2(2 * j2))],
```
throws the error.

**Comment by nikolasibalic** [comment]
Hi @pbanner 

Thank you for issue submission. I have run
```python
from arc import *
print(wigner.Wigner6j(0.5,0.5,1,2,1,1.5))
```
and have got
```
0.28867513459481287
```
I get same when I run ```wigner.Wigner6j(1/2,1/2,1,2,1,3/2)``` (note that this is same only on Python 3.*, in Python 2 division is assumed to be integer and this would render to ```wigner.Wigner6j(0,0,1,2,1,1)``` throwing error that symbol is not triangular). 

Line 215 should not be the problem since for your test case there is a condition before in line 211
```python
abs(roundPy2(j1)-j1) < 0.1)
```
that should evaluate to false, forcing module not to used precalculated look-up table. So I am bit confused why you see the error.

@pbanner could you please let me know which Python you are using, on which OS, and share complete error trace that Python returns? Also could you please confirm that you are running latest ARC.

**Comment by pbanner** [comment]
Hi, Nikola,

Thanks for looking into this. I just upgraded ARC, and it now works fine.
For some reason I didn't think to do that. I'll tell my lab mates to do the
same; a couple of them tried the calculation and got the same error message.

Thanks again,
-Patrick

**Comment by nikolasibalic** [comment]
Hi Patrick,

Great, thank you! And don't hesitate to submit issue if you encounter any problems of even if you have question. With complicated programs like this, input from users is irreplaceable for tracking down all edge cases.

Best wishes,
Nikola
