### ISSUE TITLE
 6j-Symbol is not triangular in LevelPlot.drawSpectra()

### ISSUE THREAD

**Issue by zzpwahaha** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#45]
```python
atom = Rubidium87()
level = LevelPlot(atom)
level.makeLevels(4,6,0,3)
level.drawSpectra()
level.showPlot()
```
maybe change to 'return 0 if is not trangular' in Wiger6J

**Comment by nikolasibalic** [comment]
Let me check this one, this looks like some bug.

**Comment by nikolasibalic** [comment]
@zzpwahaha thanks for this,

It's not bug - just the call to get level diagram should be:
```python
atom = Rubidium87()
level = LevelPlot(atom)
level.makeLevels(5,6,0,3)
level.drawLevels()
level.showPlot()
```
Note that you should call ```drawLevels``` instead of ```drawSpectra``` (that function is not officially supported at the moment - it remains from some past developments). In general program stops if Wigner6J is not triangular because that usually means some entered parameters are not correct. But in this case this is probably because ```drawSpectra``` is old and should not be called (it's not actually visible in documentation).

Also note that grund state of rubidium corresponds to 5, so there is probably no reason to try to plot from n=4 (first argument of ```makeLevels```.

**Comment by zzpwahaha** [comment]
Thanks for the reply. I see.
Btw, the reason I start from 4 is to include to 4D state as it is energetically higher than 5S_{1/2}
And I thinks that is supported in plotLevels?

**Comment by nikolasibalic** [comment]
Ah yes, you are right. It is supported. I forgot for the moment these, but luckily ARC didn't. :)

**Comment by zzpwahaha** [comment]
Thanks :)
