### ISSUE TITLE
Wavefunction::plot2D should it plot Psi instead of r*Psi

### ISSUE THREAD

**Issue by zzpwahaha** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#49]
Hi Nikola
In the Wavefunction class, the plot2D funciton plot the wavefunction in the spherical coordinate on the 2d cartesian plane. Then it make sense to me to only plot the Psi^2 rather than including the volume factor r^2 since this is in cartesian coordinate.

**Comment by nikolasibalic** [comment]
Hi Zhenpu (@zzpwahaha ),

Thank you for this point. I think there is no really correct way to do it, it depends what you need. Often in publications |r psi+|^2 + |r psi-|^2 are plotted. But if for calculations you need to access directly just a wavefunction you can do that too in ARC with ```getPsi(x,y,z)``` as the following code shows:

```python
atom = Rubidium()
n = 10; l=1; j=1.5;  mj=1.5;
wf = Wavefunction(atom, [[n,l,j,mj]], [1])

z=0  # where we cut throught the electron cloud
x = np.linspace(-180,180,200)  # in units of Bohr radius (a0)
y = np.linspace(-180,180,200)
x, y = np.meshgrid(x, y)
f = np.zeros((len(x),len(x)))

for i,rowx in enumerate(x):
    for j, xval in enumerate(x[i]):
        yval = y[i][j]
        wfP, wfM = wf.getPsi(xval, yval, z)
        f[i][j] = float(np.power(np.abs(wfP), 2) + np.power(np.abs(wfM), 2))

fig = plt.figure(figsize=(6,4))
ax = fig.add_subplot(1,1,1)
cp = ax.pcolor(x, y, f,
               vmin=0, vmax=f.max(), cmap='viridis')

plt.show()
```
I hope this fits your use case.
Best wishes,
Nikola

**Comment by zzpwahaha** [comment]
Thanks for your reply, Nikola
Yes. I agree part of your point. But my view is that since we are plotting a wavefunction in a 2D slice in the Cartesian coordinate, it make sense to plot the |Psi+|^2 + |Psi-|^2 rather than r^2*(|Psi+|^2 + |Psi-|^2), becasue the latter one is accounting for the spherical coordinate where the r is specified as the distance from the origin. In the spherical case, the radial part of the wavefunction is heavily peaked at outter region which comes from the r^2 volume factor in spherical coordinate. But in Cartesian, there is not such factor and the plot of r^2*(|Psi+|^2 + |Psi-|^2) in 2D cartesian slice is quite misleading because of the r^2 volume factor that should not appear in the Cartesian coord.

Hope I made myself clear.
Best,
Zhenpu

**Comment by nikolasibalic** [comment]
Hi Zhenpu,

Thank you for your feedback. I don't think that choice of coordinate system on its own should be the key differentiating factor. ```plot2D``` is just a helpful function for a common wave function visualisation in different planes cutting through the nucleus. Multiplication of |psi|^2 with r^2 is often used for visualisation in order the enhance visibility of the whole wave function. Otherwise there isn't much to be seen as the wave function amplitude quickly drops.
I agree that there are situations where multiplication with r^2 might not simply relate to actual wave function in 3D, e.g. when one cannot simply rotate function around some symmetry axis to get idea of the whole density distribution in the cloud,  but these are not directly related to which coordinate system one uses at the end to plot results. In any case, there is ```getPsi``` for generic use and plotting as user that can be used as above.

I think that API as it stands supports all possible uses, and this is just a convention what functions one might add to provide quick common visualisations.

Many thanks once again for feedback and discussion!
Nikola
