### ISSUE TITLE
The definition of polarisability in the arc primer does not match that returned by the getPolarizability command

### ISSUE THREAD

**Issue by gerardhiggins** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#5]
The value returned by getPolarizability is 2/3 the size of alpha_0 here:
http://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/_static/Rydberg_atoms_a_primer.html#Rydberg-Atom-Stark-Shifts

For example see the python file that is inside the attached zip folder (I can't directly attach a python file).
[polarisability_check.zip](https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/files/732222/polarisability_check.zip)

**Comment by gerardhiggins** [comment]
Equation 2.8 here corroborates including the factor of 2/3.
http://mro.massey.ac.nz/xmlui/bitstream/handle/10179/1694/02_whole.pdf?sequence=1&isAllowed=y

**Comment by nikolasibalic** [comment]
Thank you for your comments. I agree partially with them:

1. There should be a factor of 2 e^2 in front of the expression for polarizability in example notebook: http://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/_static/Rydberg_atoms_a_primer.html#Rydberg-Atom-Stark-Shifts
2. However, there should not be the factor of 1/3. This is different compared to the cited eq. (2.8) from the linked thesis because they are doing there averaging over orientations of the molecule. Here, we consider atoms whose quantization axis is directed along the electric field (q=0). Therefore, we don't include all mj2, just mj2 = mj1, and sum only over n2, l2

In your example if you add factor of 2 in calculation (to correct for 1.) and don't do averaging over all mj2, but use only mj2 = mj1 (corresponding to q=0; electric field directed along the quantiazation axis), you get that calculated result and result returned by the program match. The coresponding correction of your code is:

```
atom=Rubidium()
pol2=0.
l2=1
mj2=mj1 # ISSUE 2: fixed orientation, E field along quantization axis
q = 0
for n2 in range(n1-10,n1+10):
    for j2 in [0.5,1.5]:
        energy_difference = ( atom.getEnergy(n2,l2,j2) - atom.getEnergy(n1,l1,j1)) / 27.2114    # convert eV to Hartree
        dipole_matrix_element = atom.getDipoleMatrixElement(n1,l1,j1,mj1,n2,l2,j2,mj2,q)
        # ISSUE 1: added factor of 2
        pol2 += 2*dipole_matrix_element**2 / energy_difference
pol2_au = pol2
pol2 = (pol2)*polarisability_atomic_units/h*1e4/1e6

print("polarisability calculated from dipole matrix elements")
print("%.2f MHz cm^2 / V^2" % (pol2))
print("%.2e atomic units  " % (pol2_au))
print
```

I will correct the equation in example notebook and close this issue. Thank you for spotting this mistake!

Just to clarify for other readers: polarizabilities from ARC were correct (as they are checked with experimental values), but the question is the equation in the notebook.
