### ISSUE TITLE
Pondermotive polarizability conventional constant factor

### ISSUE THREAD

**Issue by zzpwahaha** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#50]
Hi Nikola
I think there is an extra factor in the pondermotive polarizability. Since in AC field, the polarizability is defined as U = 1/4*\alpha_{AC} * E^2 compared to that of DC: U = 1/2*\alpha_{DC} * E^2. It is just a minor factor of 2 but I think it still worth to point it out.
https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/blob/3673a60d4dcb25b31784663cb72d00b9c2176fbd/arc/calculations_atom_single.py#L2555

**Comment by nikolasibalic** [comment]
Hi @zzpwahaha ,

As it happens with polarizability definitions, there might be in literature multiple versions differing by factor of 2 from one another. It is similar situation as with static (DC) polarizability where also some people defined it with or without additional factor of 2.

The definition used in ARC is consistent with e.g. [this paper](https://doi.org/10.1088/0953-4075/44/18/184010) .

In order to prevent confusion, clarification should be added in documentation (in addition to what is written in [manuscript](https://arxiv.org/pdf/2007.12016.pdf) detailing new version ).
