### ISSUE TITLE
numpy.core.multiarray failed to import (Question)

### ISSUE THREAD

**Issue by BerrebiHuji** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#63]
Hey, 
I used Conda instead of pip to download the package. 
There's an error running the notebook code:

`atom=Caesium()`

`
C:\ProgramData\Anaconda3\lib\site-packages\arc\alkali_atom_functions.py in __init__(self, preferQuantumDefects, cpp_numerov)
      200 
      201         if self.cpp_numerov:
--> 202             from .arc_c_extensions import NumerovWavefunction
      203             self.NumerovWavefunction = NumerovWavefunction
      204 

ImportError: numpy.core.multiarray failed to import`

As I have read other issues, the problem is with the C compiler, but the answers have only addressed pip users.

(I'm using python 3.8)

**Comment by nikolasibalic** [comment]
Hello @BerrebiHuji 

Conda ARC package is old and outdated. I will try to delete that old package there not to cause future confusion.

Could you please get ARC with pip ? That should work. Let me know.

**Comment by nikolasibalic** [comment]
Hi @BerrebiHuji , I am also bit confused how you installed ARC with conda - could you please share that I would be interested ? Because conda package of ARC that I made long time ago has been deleted (I verified now), and I don't see someone else maintains ARC conda package (I checked on anaconda.org).

In any case supported installation method is via pip, and there are pre-build wheels for all current OS and Python versions (if something is missing, please let me know and I can add; Windwos Python 3.8 is supported there currently, which I think you have).

**Comment by BerrebiHuji** [comment]
@nikolasibalic 
I appreciate your quick response!

Your right, it turns out I used the pip command in my anaconda environment to install the package and I got confused over that.
(In other words, my python (Pycharm) interpreter is my anaconda 'root' environment)

After removing the package and reinstalling it again (using pip), my problem persists.
Attached is the error message which I am getting

![image](https://user-images.githubusercontent.com/39646310/116540451-d55b1400-a8f2-11eb-8ed2-f224dcd90a9f.png)

**Comment by nikolasibalic** [comment]
@BerrebiHuji 
Could you please let me know what numpy version you have ? 
Last time we had this it was version problem so have to check that.

**Comment by nikolasibalic** [comment]
Please check if updating numpy to the latest version in conda resolves this. (should be 1.19.2)

**Comment by BerrebiHuji** [comment]
my version is 1.19.2
![image](https://user-images.githubusercontent.com/39646310/116542495-5d421d80-a8f5-11eb-956e-933d87c93ca8.png)

**Comment by nikolasibalic** [comment]
Thanks, I will switch on Windows machine to try to reproduce this. Will let you know.

**Comment by nikolasibalic** [comment]
@BerrebiHuji 
I was able to reproduce your problem on Windows 10, Python 3.8, fresh Anaconda installation.

Looking online I found that this is common problem with numpy 1.19.2. it seems on Windows as multiple packages report this on stackoverflow (see [this](https://stackoverflow.com/questions/52243981/problem-with-cv2-numpy-core-multiarray-failed-to-import)). It is very similar to problem we had on Windows and conda with 1.16 before (issue #25 ). Solutoin is to update numpy, but since conda channel doesn't have latest numpy, you should use conda-forge.

I solved it with
```
conda uninstall numpy
conda install -c conda-forge numpy scipy sympy mpmath
```
If any additional missing packages are reported after numpy uninstall, just install them too.

Please let me know: does this works for you ?

**Comment by BerrebiHuji** [comment]
Yes!
Thank you
