### ISSUE TITLE
Something  maybe wrong when calculate the Polarizability (stark map)

### ISSUE THREAD

**Issue by linxiaodong-lom** [nikolasibalic/ARC-Alkali-Rydberg-Calculator#76]
When I consider more states, the result seeming to be worse and the polarizability seems like don't converge.See code below

```python
calc = StarkMap(Rubidium())
calc.defineBasis(50, 0, 1/2, 1/2, 45, 55, 20, Bz=0, progressOutput=False, debugOutput=False, s=0.5)
calc.diagonalise(np.linspace(00.,6000,600))
print("%.5f MHz cm^2 / V^2 " % calc.getPolarizability())
```

 I get  polarizability=21.52388 MHz cm^2 / V^2 

```python
calc = StarkMap(Rubidium())
calc.defineBasis(50, 0, 1/2, 1/2, 40, 60, 20, Bz=0, progressOutput=False, debugOutput=False, s=0.5)
calc.diagonalise(np.linspace(00.,6000,600))
print("%.5f MHz cm^2 / V^2 " % calc.getPolarizability())
```

I get polarizability = 8.60878 MHz cm^2 / V^2 

I also calculate the polarization  using the perturbation method. and I get polarizabilty = 25.374048 MHz cm^2 / V^2

I think the result is more accurate when I consider more states. Is something wrong?

**Comment by nikolasibalic** [comment]
Hi @linxiaodong-lom , thank you for question.

calc.diagonalise and calc.getPolarizability() will diagonalise Stark map in a given range of electric fields and then try to fit target state to that plot. Problem in your calculation is that you are taking very high electric fields, where simple Stark shift based on polarisability is insufficiant to explain state energy. You can see that if you add plots of the states in the requested range of E-fields:

```python
from arc import *

calc = StarkMap(Rubidium())
calc.defineBasis(50, 0, 1/2, 1/2, 45, 55, 20, Bz=0, progressOutput=True, debugOutput=False, s=0.5)
calc.diagonalise(np.linspace(00.,6000,600))

calc.plotLevelDiagram(progressOutput=True,units=1,highlightState = True)
calc.showPlot(interactive = False)

print("%.5f MHz cm^2 / V^2 " % calc.getPolarizability(showPlot=True))
```
```
Found  410  states.
Generating matrix...
100%

plotting...
```
![im1](https://user-images.githubusercontent.com/24477754/128628863-6200344f-4456-4a49-8b24-07c0e48fd69b.png)
![im2](https://user-images.githubusercontent.com/24477754/128628865-66f1474a-c998-42ea-92c1-1c8140045061.png)

```
21.52384 MHz cm^2 / V^2 
```

You see from above that in the range of E fields considered state is strongly admixed with other states (plus the basis is still to small for strong E fields).

So if you are searching for a comparison with pertubative calculations, you should limit the range of E fields to the range where fields are small enough that such calculation is correct. For example by going up to 1 V/cm we get:

```python
from arc import *

calc = StarkMap(Rubidium())
calc.defineBasis(50, 0, 1/2, 1/2, 45, 55, 20, Bz=0, progressOutput=True, debugOutput=False, s=0.5)
calc.diagonalise(np.linspace(00.,100,600))

calc.plotLevelDiagram(progressOutput=True,units=1,highlightState = True)
calc.showPlot(interactive = False)

print("%.5f MHz cm^2 / V^2 " % calc.getPolarizability(showPlot=True))
```
```
Found  410  states.
Generating matrix...
100%

plotting...
```
![im3](https://user-images.githubusercontent.com/24477754/128628868-144812b0-3c53-4af0-a815-c694315f9525.png)
![im4](https://user-images.githubusercontent.com/24477754/128628869-61ade2c1-1f23-4a6a-bf7a-f5d5c264f739.png)

```
50.60900 MHz cm^2 / V^2 
```

You will get similar results now with expanded basis too (`50.61244 MHz cm^2 / V^2`). This is in agreement with pertubative result you mentioned, because polarisability in ARC is related by definition  `1/2*alpha*Efield^2` to energy shift, [as explained in documentation](https://arc-alkali-rydberg-calculator.readthedocs.io/en/latest/calculations_atoms_single.html#arc.calculations_atom_single.StarkMap.getPolarizability), whereas I guess that in your calculation your definition of polarisability includes factor of 1/2 in it.

I hope this resolves this question. Let me know if this is fine with you.

**Comment by linxiaodong-lom** [comment]
Thanks a lot!
